name: Train Iris Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run training script
      - name: Train model
        run: python training.py

      # List files to verify model.pkl is created
      - name: List files in the directory
        run: ls -la

      # Upload model as an artifact
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: iris-model
          path: model.pkl

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Commit and push model.pkl to the repository
      - name: Commit and push model.pkl
        run: |
          git add model.pkl
          git commit -m "Add trained model"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
